#
# Makefile for the Mstar MSG2xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_common.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_main.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_qcom.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_self_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_self_mp_test.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_utility_adaption.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_platform_interface.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_platform_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV) += mstar_drv_jni_interface.o